/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JRunJobDialog.java
 *
 * Created on Aug 4, 2010, 6:17:28 PM
 */
package org.me.hadoop.wsclient.ui;

import java.util.HashMap;
import java.util.Map;
import org.me.hadoop.wsclient.ProgressableUI;

/**
 *
 * @author Aaron
 */
public class JRunJobDialog extends javax.swing.JDialog implements ProgressableUI {

    private RunJobTask task;
    private Map<String, String> properties;

    /** Creates new form JRunJobDialog */
    public JRunJobDialog(java.awt.Frame parent, boolean modal, RunJobTask task) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.task = task;
        properties = new HashMap<String, String>();
        properties.put("job.forget", Boolean.toString(false));
    }

    @Override
    public void setProgress(String message, boolean indeterminate, int currentstep,
            int totalsteps) {
        jRunJobLabel.setText(message);
        jRunJobProgressBar.setIndeterminate(indeterminate);
        if (!indeterminate) {
            jRunJobProgressBar.setMinimum(0);
            jRunJobProgressBar.setMaximum(totalsteps);
            jRunJobProgressBar.setValue(currentstep);
        }
    }

    @Override
    public boolean getProperty(String key) {
        if (properties.containsKey(key)) {
            return Boolean.parseBoolean(properties.get(key));
        }
        return false;
    }

    @Override
    public String getProperty(String key, String value) {
        if (properties.containsKey(key)) {
            return properties.get(key);
        }
        return value;
    }

    @Override
    public void setProperty(String key, String value) {
        if ((value != null) && (value.trim().length() != 0)) {
            properties.put(key, value);
        }
    }

    @Override
    public void failed(String message) {
        setProperty("job.failure", message);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRunJobProgressBar = new javax.swing.JProgressBar();
        jRunJobLabel = new javax.swing.JLabel();
        jForgetJobButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.me.hadoop.wsclient.ui.HadoopWSClient.class).getContext().getResourceMap(JRunJobDialog.class);
        setTitle(resourceMap.getString("runJobBox.title")); // NOI18N
        setName("runJobBox"); // NOI18N

        jRunJobProgressBar.setName("jRunJobProgressBar"); // NOI18N

        jRunJobLabel.setText(resourceMap.getString("jRunJobLabel.text")); // NOI18N
        jRunJobLabel.setName("jRunJobLabel"); // NOI18N

        jForgetJobButton.setText(resourceMap.getString("jForgetJobButton.text")); // NOI18N
        jForgetJobButton.setName("jForgetJobButton"); // NOI18N
        jForgetJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jForgetJobButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jForgetJobButton, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRunJobProgressBar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jRunJobLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRunJobLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRunJobProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jForgetJobButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jForgetJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jForgetJobButtonActionPerformed
        // TODO add your handling code here:
        jRunJobLabel.setText("Forgetting job...");
        jForgetJobButton.setEnabled(false);
        properties.put("job.forget", Boolean.toString(true));
        task.interrupt();
    }//GEN-LAST:event_jForgetJobButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jForgetJobButton;
    private javax.swing.JLabel jRunJobLabel;
    private javax.swing.JProgressBar jRunJobProgressBar;
    // End of variables declaration//GEN-END:variables
}
