/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDataCreator1Page.java
 *
 * Created on 14/08/2009, 9:27:00 AM
 */
package org.me.hadoop.wsclient.ui.wizards;

import java.awt.Component;
import javax.swing.JFileChooser;
import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author Aaron
 */
public class JDataCreator1Page extends WizardPage {

    /** Creates new form JDataCreator1Page */
    public JDataCreator1Page() {
        initComponents();
    }

    public static String getDescription() {
        return "Choose Directory";
    }

    @Override
    protected String validateContents(Component component, Object event) {
        if ((component == null) || (component == jInputDirChooser)) {
            if (jInputDirChooser.getSelectedFile() == null) {
                return "Choose the directory that contains input files for " +
                        "a job.";
            }
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInputDirChooser = new javax.swing.JFileChooser();

        setName("jIDCFirstPage"); // NOI18N

        jInputDirChooser.setControlButtonsAreShown(false);
        jInputDirChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jInputDirChooser.setName("jInputDirChooser"); // NOI18N
        jInputDirChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jInputDirChooserPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInputDirChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInputDirChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jInputDirChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jInputDirChooserPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals(JFileChooser.SELECTED_FILE_CHANGED_PROPERTY)) {
            if (jInputDirChooser.getSelectedFile() != null) {
                String path = jInputDirChooser.getSelectedFile().getAbsolutePath();
                putWizardData(jInputDirChooser.getName(), path);
            }
        }
    }//GEN-LAST:event_jInputDirChooserPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jInputDirChooser;
    // End of variables declaration//GEN-END:variables
}
