/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JModelCreatorStreamPage.java
 *
 * Created on 14/08/2009, 9:40:58 AM
 */
package org.me.hadoop.wsclient.ui.wizards;

import java.awt.Component;
import java.io.File;
import java.util.Collection;
import org.me.hadoop.utils.CommonsIO;
import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author Aaron
 */
public class JModelCreatorStreamPage extends WizardPage {

    private String dirname = "";

    /** Creates new form JModelCreatorStreamPage */
    public JModelCreatorStreamPage() {
        initComponents();
    }

    public static String getDescription() {
        return "Fill In Compulsory Details";
    }

    @Override
    protected String validateContents(Component component, Object event) {
        if ((component == jMethodComboBox) || (component == jNameTextField) ||
                (component == jLanguageComboBox) || (component == jMapperFileComboBox) ||
                (component == null)) {
            if (!jMethodComboBox.getSelectedItem().equals("hadoop.streaming")) {
                return "Method of the model must be \"hadoop.streaming\".";
            }
            if (jNameTextField.getText().trim().length() == 0) {
                return "Fill in the name of the model.";
            }
            if (jLanguageComboBox.getSelectedIndex() == -1) {
                return "Choose the language for the model.";
            }
            if (jMapperFileComboBox.getSelectedIndex() == -1) {
                return "Choose the mapper file for the model.";
            }
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMethodLabel = new javax.swing.JLabel();
        jMethodComboBox = new javax.swing.JComboBox();
        jNameLabel = new javax.swing.JLabel();
        jNameTextField = new javax.swing.JTextField();
        jLanguageLabel = new javax.swing.JLabel();
        jLanguageComboBox = new javax.swing.JComboBox();
        jMapperFileLabel = new javax.swing.JLabel();
        jMapperFileComboBox = new javax.swing.JComboBox();
        jReducerFileLabel = new javax.swing.JLabel();
        jReducerFileComboBox = new javax.swing.JComboBox();

        setName("jStreamingMCSecondPage"); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jStreamingMCSecondPageFocusGained(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.me.hadoop.wsclient.ui.HadoopWSClient.class).getContext().getResourceMap(JModelCreatorStreamPage.class);
        jMethodLabel.setText(resourceMap.getString("jMethodLabel.text")); // NOI18N
        jMethodLabel.setName("jMethodLabel"); // NOI18N

        jMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hadoop.streaming", "hadoop.jar" }));
        jMethodComboBox.setEnabled(false);
        jMethodComboBox.setName("jMethodComboBox"); // NOI18N

        jNameLabel.setText(resourceMap.getString("jNameLabel.text")); // NOI18N
        jNameLabel.setName("jNameLabel"); // NOI18N

        jNameTextField.setText(resourceMap.getString("jNameTextField.text")); // NOI18N
        jNameTextField.setName("jNameTextField"); // NOI18N

        jLanguageLabel.setText(resourceMap.getString("jLanguageLabel.text")); // NOI18N
        jLanguageLabel.setName("jLanguageLabel"); // NOI18N

        jLanguageComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Python" }));
        jLanguageComboBox.setName("jLanguageComboBox"); // NOI18N

        jMapperFileLabel.setText(resourceMap.getString("jMapperFileLabel.text")); // NOI18N
        jMapperFileLabel.setName("jMapperFileLabel"); // NOI18N

        jMapperFileComboBox.setName("jMapperFileComboBox"); // NOI18N

        jReducerFileLabel.setText(resourceMap.getString("jReducerFileLabel.text")); // NOI18N
        jReducerFileLabel.setName("jReducerFileLabel"); // NOI18N

        jReducerFileComboBox.setName("jReducerFileComboBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMethodLabel)
                    .addComponent(jNameLabel)
                    .addComponent(jLanguageLabel)
                    .addComponent(jMapperFileLabel)
                    .addComponent(jReducerFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jReducerFileComboBox, 0, 283, Short.MAX_VALUE)
                    .addComponent(jMapperFileComboBox, 0, 283, Short.MAX_VALUE)
                    .addComponent(jLanguageComboBox, 0, 283, Short.MAX_VALUE)
                    .addComponent(jNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jMethodComboBox, 0, 283, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMethodLabel)
                    .addComponent(jMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameLabel)
                    .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLanguageLabel)
                    .addComponent(jLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMapperFileLabel)
                    .addComponent(jMapperFileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReducerFileLabel)
                    .addComponent(jReducerFileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jStreamingMCSecondPageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStreamingMCSecondPageFocusGained
        // TODO add your handling code here:
        String value = (String) getWizardData("jModelDirChooser");
        if (!dirname.equals(value)) {
            jMapperFileComboBox.removeAllItems();
            jReducerFileComboBox.removeAllItems();
            Collection<File> files = CommonsIO.listFiles(value, new String[]{"py"});
            if ((files != null) && (!files.isEmpty())) {
                for (File file : files) {
                    String path = file.getAbsolutePath();
                    jMapperFileComboBox.addItem(path.substring(value.length() + 1));
                    jReducerFileComboBox.addItem(path.substring(value.length() + 1));
                }
                jMapperFileComboBox.setSelectedIndex(-1);
                jReducerFileComboBox.setSelectedIndex(-1);
                dirname = value;
            }
        }
    }//GEN-LAST:event_jStreamingMCSecondPageFocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jLanguageComboBox;
    private javax.swing.JLabel jLanguageLabel;
    private javax.swing.JComboBox jMapperFileComboBox;
    private javax.swing.JLabel jMapperFileLabel;
    private javax.swing.JComboBox jMethodComboBox;
    private javax.swing.JLabel jMethodLabel;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameTextField;
    private javax.swing.JComboBox jReducerFileComboBox;
    private javax.swing.JLabel jReducerFileLabel;
    // End of variables declaration//GEN-END:variables
}
