/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JModelCreator3Page.java
 *
 * Created on 14/08/2009, 9:37:17 AM
 */
package org.me.hadoop.wsclient.ui.wizards;

import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author Aaron
 */
public class JModelCreator3Page extends WizardPage {

    /** Creates new form JModelCreator3Page */
    public JModelCreator3Page() {
        initComponents();
    }

    public static String getDescription() {
        return "Fill In Optional Details";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jVersionLabel = new javax.swing.JLabel();
        jVersionTextField = new javax.swing.JTextField();
        jAuthorLabel = new javax.swing.JLabel();
        jAuthorTextField = new javax.swing.JTextField();
        jDescriptionLabel = new javax.swing.JLabel();
        jDescriptionTextField = new javax.swing.JTextField();

        setName("jMCLastPage"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.me.hadoop.wsclient.ui.HadoopWSClient.class).getContext().getResourceMap(JModelCreator3Page.class);
        jVersionLabel.setText(resourceMap.getString("jVersionLabel.text")); // NOI18N
        jVersionLabel.setName("jVersionLabel"); // NOI18N

        jVersionTextField.setText(resourceMap.getString("jVersionTextField.text")); // NOI18N
        jVersionTextField.setName("jVersionTextField"); // NOI18N

        jAuthorLabel.setText(resourceMap.getString("jAuthorLabel.text")); // NOI18N
        jAuthorLabel.setName("jAuthorLabel"); // NOI18N

        jAuthorTextField.setText(resourceMap.getString("jAuthorTextField.text")); // NOI18N
        jAuthorTextField.setName("jAuthorTextField"); // NOI18N

        jDescriptionLabel.setText(resourceMap.getString("jDescriptionLabel.text")); // NOI18N
        jDescriptionLabel.setName("jDescriptionLabel"); // NOI18N

        jDescriptionTextField.setText(resourceMap.getString("jDescriptionTextField.text")); // NOI18N
        jDescriptionTextField.setName("jDescriptionTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jVersionLabel)
                    .addComponent(jAuthorLabel)
                    .addComponent(jDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDescriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jAuthorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jVersionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVersionLabel)
                    .addComponent(jVersionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAuthorLabel)
                    .addComponent(jAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDescriptionLabel)
                    .addComponent(jDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAuthorLabel;
    private javax.swing.JTextField jAuthorTextField;
    private javax.swing.JLabel jDescriptionLabel;
    private javax.swing.JTextField jDescriptionTextField;
    private javax.swing.JLabel jVersionLabel;
    private javax.swing.JTextField jVersionTextField;
    // End of variables declaration//GEN-END:variables
}
